// Verbatim v1 snapshot of the published agreements. Source of truth lives in
// the workspace markdown files (reimagine-privacy-policy.md /
// reimagine-terms-of-service.md). Future edits start there, then propagate
// here, and PRIVACY_VERSION / TOS_VERSION are bumped per src/config/legal.js.

export const PRIVACY_MD = `# Reimagine Data Privacy and Usage Agreement

**Effective date:** May 15, 2026
**Last updated:** June 24, 2026

This agreement explains what information Reimagine collects when you use the product, how we use it, who we share it with, and the choices you have. Reimagine is a career strategy tool operated by Decima LLC, doing business as Career Club. When this document says "we," "us," or "Reimagine," it refers to Decima LLC (dba Career Club) as the operator of the product. When it says "you" or "your," it refers to you as a person using Reimagine.

This Privacy Agreement applies to your use of the Reimagine product. Career Club Corner, our separate newsletter, operates under its own subscription terms and is not covered by this document.

By creating an account or using Reimagine, you agree to the practices described here. If you do not agree with these practices, please do not use the product.

## 1. What we collect

We collect three categories of information.

**Information you provide directly.** This is the information you type or upload into Reimagine. It includes:

- Your email address, used to create your account and to send sign-in links.
- The narrative and reflection content you enter, including descriptions of your life chapters, achievements, values, work history, aspirations, and any free-text responses to prompts inside the product.
- Any corrections or feedback you submit when you tell us an output is off the mark or could be better.
- Optional contact information you share when you reply to us or request support.

**Information generated by your use of Reimagine.** This includes:

- The outputs the product generates for you, such as career framings, summaries, lane analyses, and playbooks.
- A record of which prompts you ran, which outputs you saved or revised, and the timestamps associated with that activity.
- Session tokens that keep you signed in across devices.

**Technical information.** When you use Reimagine, we automatically receive:

- Basic device and browser information, such as browser type and operating system.
- IP address, used for security and to detect unusual sign-in activity.
- General usage metrics, such as which pages or steps were viewed and how long sessions lasted.

We also collect anonymous behavioral analytics (which sections of the product you visit, how long generations take, which options you pick during the Bridge Story step) that we use to monitor product health and improve the experience. These events do not include your name, email, or content. We forward this anonymous data to a private analytics store that we control. This anonymous analytics stream is distinct from the de-identified review of coaching and chat conversations described in Section 2, which is a separate activity governed by that section.

We do not knowingly collect government identifiers, financial account numbers, health information, or precise location data. If any of these appear in content you type into the product, you do so voluntarily and we treat that content the same way we treat the rest of your narrative inputs.

## 2. How we use your information

We use the information described above to:

- Provide the product to you, which includes generating personalized outputs based on the narrative content you enter.
- Authenticate you, by sending sign-in links to your email and maintaining your session.
- Sync your profile and your outputs across the devices you sign into.
- Improve Reimagine, by reviewing aggregated usage patterns and by reviewing the corrections users submit so the product gets better at the things people actually need.
- Communicate with you about your account, including product updates, security notices, and replies to messages you send us.
- Protect the product and our users, including detecting fraud, abuse, and security issues.
- Comply with legal obligations.

**Reviewing conversations to improve coaching.** To evaluate and improve the quality and safety of our coaching, chat, and help features, authorized Career Club personnel may review the content of your interactions with these features — the questions and messages you send, the responses you receive, and any ratings or feedback you provide. We carry out this review using de-identified records: your name, email address, and account identifiers are removed before the content is reviewed, so reviewers see the conversation and your feedback but not who you are. We use what we learn only to assess and improve the service. We do not sell this content, we do not use it to train AI models, and we do not use this review to identify, target, or contact you individually.

We do not sell your personal information. We do not use your narrative content to target advertising, and we do not share your content with advertisers. We do not rent or trade your contact information.

## 3. How we share your information

We share information only in the following circumstances.

**With service providers who help us run Reimagine.** We use third-party vendors to host the application, store your account and profile data, process AI prompts, deliver email, and handle related operational needs. These vendors are contractually limited to using your information only to provide services to us. You can request a current list of the categories of service providers we use by contacting us at the address in Section 13.

**With AI processing providers.** Reimagine uses an AI provider to generate the outputs you see. When you run a prompt, the relevant inputs are transmitted to that provider for processing. The provider does not train its underlying models on the content you submit through our integration. We describe this in more detail in Section 4.

**For legal reasons.** We may disclose information when we have a good-faith belief that doing so is necessary to comply with a law, regulation, legal process, or governmental request; to enforce our terms; to protect the safety of any person; or to address fraud, security, or technical issues.

**In connection with a business transfer.** If we are involved in a merger, acquisition, financing, or sale of assets, your information may be transferred as part of that transaction. If that happens, we will provide notice and your information will remain subject to this agreement unless you agree to a different one.

**With your consent.** We may share information in other ways if you direct us to or give us your permission.

## 4. AI processing

Reimagine relies on a third-party AI provider to generate the outputs you see. This is the core of how the product works, so we want to be specific about what that means for your data.

When you submit a prompt or run a step inside Reimagine, the relevant content you have provided is sent to our AI provider's servers for processing. That content is used to generate a response, which is returned to Reimagine and shown to you. The provider receives the content, processes it, and returns the response.

Our AI provider, under the terms of the agreement we have with them as a developer, does not use the content sent through our integration to train or improve their underlying AI models. Your inputs are not added to a public training corpus by virtue of using Reimagine.

The outputs the AI generates for you are stored on your Reimagine account so you can return to them later. You can delete them at any time, which is described in Section 8.

## 5. Where your information is stored and how we protect it

Your account data, your profile, your inputs, and the outputs Reimagine generates are stored on cloud infrastructure provided by our service providers. Servers are located in the United States. If you access Reimagine from outside the United States, your information will be transferred to and stored in the United States.

We protect your information using industry-standard safeguards, including:

- Encryption of data in transit using HTTPS.
- Encryption of data at rest in the databases where we store it.
- Passwordless authentication using time-limited magic links sent to your email, which means we do not store passwords that could be stolen.
- Access controls that limit which people on our team can view production data, and audit trails when they do.

No system is perfectly secure. We work to protect your information, and we cannot guarantee absolute security. If we become aware of a breach that affects your information, we will notify you as required by applicable law.

## 6. Cookies and local storage

Reimagine uses cookies and your browser's local storage to:

- Keep you signed in.
- Remember your preferences and progress through the product.
- Measure aggregated usage so we can understand how people use Reimagine.

We do not use advertising cookies or third-party trackers for marketing purposes. You can clear cookies and local storage in your browser settings; doing so will sign you out and may reset your in-product preferences.

## 7. How long we keep your information

We keep your information for as long as your account is active and for a reasonable period after that, so you can come back to your work and so we can meet our legal and operational obligations.

- **Account information and profile data:** retained while your account is active.
- **Inputs and outputs you have saved:** retained while your account is active, or until you delete them.
- **Corrections and feedback you submit:** retained on an ongoing basis so we can improve the product. Where possible, we strip identifying information from feedback used for product improvement.
- **Technical logs:** retained for a limited period (typically 30 to 90 days) for security and operational purposes.
- **Information we are legally required to keep:** retained for the period required by law.

If you delete your account, we will delete your account information, profile, inputs, and outputs from our active systems within a reasonable period (typically 30 days). Backups may persist for an additional period before being overwritten in the normal course of operation.

## 8. Your rights and choices

You have the following rights with respect to your information.

**Access.** You can view your account information and the inputs and outputs stored in your profile at any time inside the product.

**Correction.** You can edit your profile and your inputs inside the product. If you need to correct information you cannot edit yourself, contact us using the address in Section 13.

**Deletion.** You can delete individual inputs, outputs, and saved items from inside the product. You can delete your entire account by writing to us at the contact address in Section 13. When you delete your account, we will delete the information described in Section 7.

**Export.** You can request a copy of the information associated with your account by writing to us. We will provide it in a commonly used machine-readable format.

**Opt out of communications.** Account-related emails (such as sign-in links and security notices) are part of the service. Any product updates or marketing emails will include an unsubscribe link.

**Withdraw consent.** Where we rely on your consent to process your information, you can withdraw that consent at any time. This will not affect the lawfulness of processing carried out before you withdrew it.

**Rights under stronger data protection laws.** If you live in a jurisdiction with comprehensive data protection law, including the European Union (under the General Data Protection Regulation, or GDPR), the United Kingdom (UK GDPR), Switzerland (the Federal Act on Data Protection, or FADP), and certain US states such as California (the California Consumer Privacy Act, or CCPA), you may have additional rights under your local law. These commonly include the right to access the personal information we hold about you, the right to correct inaccurate information (rectification), the right to request deletion (also called erasure or the right to be forgotten), the right to receive your information in a portable, machine-readable format, the right to object to certain uses of your information, the right not to be discriminated against for exercising any of these rights, and the right to lodge a complaint with your local data protection authority.

To exercise any of these rights, write to us at info@career.club. We will verify your identity and respond within the time required by your applicable law, typically within 30 to 45 days.

## 9. Children's privacy

Reimagine is intended for adults. We do not knowingly collect information from children under the age of 16. If you believe a child has provided information to Reimagine, please contact us and we will delete it.

## 10. International users

Reimagine is operated from the United States. If you use Reimagine from outside the United States, you understand that your information will be transferred to, stored in, and processed in the United States. Data protection laws in the United States may differ from those in your country.

## 11. Third-party services

Reimagine may include links to or integrations with third-party websites and services. We do not control those services and are not responsible for their privacy practices. This agreement applies only to Reimagine. Review the privacy policies of any third-party services you use.

## 12. Changes to this agreement

We may update this agreement from time to time. When we do, we will revise the "Last updated" date at the top of the document. If we make changes that materially affect how we handle your information, we will give you advance notice by email or through an in-product message. Your continued use of Reimagine after the changes take effect means you accept the updated agreement.

## 13. How to contact us

For privacy questions, requests, or complaints, write to us at:

**Decima LLC (dba Career Club)**
Email: info@career.club

We will respond to verified requests within the time required by applicable law, and in most cases within 30 days.`;

export const TERMS_MD = `# Reimagine Terms of Service

**Effective date:** May 15, 2026
**Last updated:** May 15, 2026

These Terms of Service ("Terms") govern your use of Reimagine, a career strategy tool operated by Decima LLC, doing business as Career Club. When these Terms say "we," "us," or "Reimagine," they refer to Decima LLC (dba Career Club). When they say "you" or "your," they refer to you as a person using Reimagine.

These Terms work alongside our Privacy Agreement, which explains how we collect, use, and protect your information. By using Reimagine, you agree to both documents.

If you do not agree with these Terms, please do not use the product.

## 1. Eligibility

You must be at least 18 years old to use Reimagine and to agree to these Terms. By using Reimagine, you confirm that you meet this age requirement and that you have the legal capacity to enter into a binding agreement.

If you are using Reimagine on behalf of an organization, you confirm that you have the authority to bind that organization to these Terms.

## 2. Your account

To use Reimagine, you create an account using your email address. We send sign-in links to that address rather than asking you to set a password.

You are responsible for:

- Keeping your email account secure, since access to your email gives access to your Reimagine account.
- The content you enter into Reimagine and the activity that occurs under your account.
- Notifying us promptly if you believe your account has been accessed without your authorization.

You may not share your account with other people or let anyone else sign in as you.

## 3. What Reimagine is and what it is not

Reimagine helps you reflect on your career and develop strategy, framing, and materials to pursue opportunities that fit you. It produces text-based analysis and suggestions based on the inputs you provide.

**Reimagine is not professional advice.** The analysis and suggestions Reimagine produces are not legal advice, financial advice, medical or mental health advice, or licensed career counseling. Using Reimagine does not create a professional advisory relationship between you and us. For decisions where professional advice is appropriate, please consult a qualified professional.

**Reimagine does not guarantee outcomes.** Reimagine helps you prepare for and pursue career opportunities. It does not guarantee that you will receive a job offer, an interview, a particular salary, a promotion, or any other specific career outcome. Your results depend on many factors that no tool can control.

You are responsible for the decisions you make using Reimagine and for the actions you take in your career.

## 4. Your content and your outputs

**Your inputs belong to you.** The narrative content, reflections, and answers you type into Reimagine remain yours.

**Your outputs are yours to use.** The analysis, framings, summaries, and materials Reimagine produces for you are yours to use for your own career strategy. This includes using them in your job search, sharing them with people helping you such as a recruiter, mentor, coach, or advisor, and incorporating them into materials you create such as a resume, cover letter, or interview prep.

**What you may not do with outputs.** You may not redistribute, resell, license, or productize Reimagine outputs as a service or product of your own. You may not use Reimagine outputs to train, fine-tune, or otherwise build another AI system or competing tool.

**License to us.** To operate the product, we need a limited license to your inputs and outputs. By using Reimagine, you give us a worldwide, non-exclusive, royalty-free license to store, process, and display your content for the purpose of providing the product to you, improving the product, and complying with our legal obligations. This license ends when you delete the content or delete your account, except where we are required to retain information for legal reasons.

## 5. Acceptable use

When you use Reimagine, you agree not to:

- Use Reimagine for any purpose other than your own career strategy and reflection.
- Use Reimagine in any way that violates applicable law or the rights of others.
- Attempt to access another user's account or data.
- Probe, scan, or test the vulnerability of the product, or interfere with its security features.
- Use automated tools to scrape, crawl, or harvest content from the product.
- Reverse engineer, decompile, or attempt to extract the underlying prompts, models, or architecture of the product.
- Use Reimagine to generate content that is illegal, harassing, defamatory, or that infringes someone else's intellectual property.
- Misrepresent who you are or impersonate someone else.
- Resell or commercialize the product or your access to it.

If you become aware of someone violating these rules, please let us know at info@career.club.

## 6. Service availability and changes

We work to keep Reimagine available, but we do not guarantee uninterrupted service. From time to time we may take the product offline for maintenance, updates, or for reasons outside our control.

We may add features, remove features, or change how the product works at any time. When a change materially affects how you use Reimagine, we will give reasonable notice.

## 7. Termination

You can stop using Reimagine at any time. To delete your account, write to us at info@career.club. The data deletion practices that follow are described in our Privacy Agreement.

We may suspend or terminate your access to Reimagine if you violate these Terms, if your continued use poses a risk to us or to other users, or if we are required to do so by law. Where reasonable, we will provide notice before terminating your access. If we terminate your account, we will follow the data deletion practices described in our Privacy Agreement.

## 8. Intellectual property

Reimagine, including the product itself, its underlying prompts, design, code, branding, and the content we create (excluding your inputs and outputs), is owned by us or our licensors and is protected by applicable intellectual property laws. These Terms do not give you any rights to our intellectual property beyond your right to use the product as described.

## 9. Third-party AI provider

Reimagine relies on a third-party AI provider to generate outputs. Your use of Reimagine is also subject to that provider's acceptable use policies, which prohibit using AI to generate content that violates law or that causes harm. If your use of Reimagine violates the AI provider's acceptable use policies, we may be required to suspend your access.

## 10. Disclaimers

Reimagine is provided on an "as is" and "as available" basis. To the maximum extent permitted by law, we disclaim all warranties, whether express, implied, or statutory, including warranties of merchantability, fitness for a particular purpose, non-infringement, and any warranties arising out of course of dealing or trade practice.

We do not warrant that:

- The product will meet your specific requirements.
- The product will be uninterrupted, timely, secure, or error-free.
- The outputs Reimagine generates will be accurate, complete, or reliable for any particular purpose.

You use Reimagine at your own discretion and risk.

## 11. Limitation of liability

To the maximum extent permitted by law, we will not be liable for any indirect, incidental, consequential, special, exemplary, or punitive damages, including loss of profits, loss of revenue, loss of opportunity, loss of data, or loss of goodwill, arising out of or in connection with your use of Reimagine.

Our total cumulative liability to you for any claim arising out of or in connection with your use of Reimagine, regardless of the basis of the claim, will not exceed the greater of (a) the amount you paid to us in the twelve months preceding the event giving rise to the claim, or (b) one hundred US dollars (US$100).

Some jurisdictions do not allow the exclusion or limitation of certain damages, so some of the limitations in this section may not apply to you.

## 12. Indemnification

You agree to defend, indemnify, and hold harmless Decima LLC, its affiliates, and their respective officers, directors, employees, and agents from any claims, liabilities, damages, losses, and expenses (including reasonable legal fees) arising out of or related to:

- Your use of Reimagine in violation of these Terms.
- Your violation of any applicable law or the rights of any third party.
- Content you submit to Reimagine that infringes a third party's rights.

## 13. Governing law and dispute resolution

These Terms are governed by the laws of the State of Ohio, United States, without regard to its conflict of laws principles.

Any dispute arising out of or related to these Terms or your use of Reimagine will be brought in the state or federal courts located in Ohio, and you consent to the jurisdiction of those courts.

If you live in a jurisdiction whose law gives you the right to bring a dispute in your local courts or under your local law, nothing in this section limits that right.

## 14. Changes to these Terms

We may update these Terms from time to time. When we do, we will revise the "Last updated" date at the top of this document. If we make changes that materially affect your rights or obligations under these Terms, we will give you advance notice by email and may require you to accept the updated Terms before continuing to use the product. Minor changes (such as typo fixes, contact information updates, or clarifications that do not change your rights or obligations) will not require re-acceptance.

Your continued use of Reimagine after changes take effect means you accept the updated Terms.

## 15. Other terms

**Severability.** If any provision of these Terms is held to be unenforceable, the remaining provisions will continue in full force and effect.

**Waiver.** Our failure to enforce any provision of these Terms is not a waiver of our right to enforce that provision later.

**Assignment.** You may not assign or transfer these Terms or your account to anyone else. We may assign these Terms in connection with a merger, acquisition, financing, or sale of assets.

**Entire agreement.** These Terms, together with the Privacy Agreement, constitute the entire agreement between you and us regarding your use of Reimagine and supersede any prior agreements between us on this subject.

**Relationship between us.** Nothing in these Terms creates a partnership, joint venture, employment, or agency relationship between you and us.

## 16. How to contact us

For questions about these Terms or about Reimagine generally, write to us at:

**Decima LLC (dba Career Club)**
Email: info@career.club`;
